const PATCH_CREATE_NODE = "PATCH_CREATE_NODE";
const PATCH_REMOVE_NODE = "PATCH_REMOVE_NODE";

const PATCH_TEXT = "PATCH_TEXT";

const PATCH_REPLACE_NODE = "PATCH_REPLACE_NODE";

const PATCH_PROPS = "PATCH_PROPS";
const PATCH_CHILD = "PATCH_CHILD";

export default {
    PATCH_CREATE_NODE,
    PATCH_REMOVE_NODE,
    PATCH_TEXT,
    PATCH_REPLACE_NODE,
    PATCH_PROPS,
    PATCH_CHILD
}